"""empty message

Revision ID: 20aafdb7026b
Revises: 5ee2dee84ec9
Create Date: 2019-10-11 14:32:38.195751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20aafdb7026b'
down_revision = '5ee2dee84ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('application_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'versions', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'versions', type_='foreignkey')
    op.drop_column('versions', 'application_id')
    # ### end Alembic commands ###
